export const particles = {
    iti: 'thus, so',
    iha: 'here',
    api: 'also, even',
    ca: 'and',
    eva: 'indeed, certainly',
    hi: 'surely, indeed',
    vā: 'or',
    tu: 'but',
    na: 'not',
    vA: 'or (alternative form of vā)',
    tathA: 'thus, in that way',
    kintu: 'but, however',
    atha: 'then, now',
    athaApi: 'and also then',
    athaiva: 'then only, just then',
    atara: 'however, but',
    evaM: 'thus, in this way',
    tvam: 'you (used as particle sometimes)',
    yad: 'if',
    yatra: 'where',
};
