export const pronouns = {
    aham: 'I',
    tvam: 'you (singular)',
    asmad: 'we (exclusive)',
    yuSmad: 'you (plural)',
    saH: 'he',
    sA: 'she',
    so: 'he (alternate form)',
    saU: 'she (alternate form)',
    yad: 'who, which',
    yam: 'whom',
    yUyam: 'you (plural)',
    asmAkaM: 'our',
    yuSmAkaM: 'your (plural)',
    te: 'they (dual/plural)',
    teSu: 'them (plural)',
    tasya: 'his',
    tasmin: 'in him',
    tasyaH: 'of him',
    asmai: 'to me',
    tve: 'to you',
};
